import { CalculatorConfig } from '../models';
import { FinancialService } from '@core/math/financial.service';

const financialService = new FinancialService();

export const NPV_CONFIG: CalculatorConfig = {
    id: 'npv',
    title: 'Net Present Value',
    subtitle: 'Measure the net value of cash flows today',
    description: 'Determine the profitability of an investment by calculating the sum of discounted future cash flows minus initial investment.',
    icon: 'pie-chart',
    category: 'Analysis',
    fields: [
        { key: 'initialInvestment', label: 'Initial Investment', type: 'number', defaultValue: 10000, prefix: '$', required: true, min: 0 },
        { key: 'cashFlows', label: 'Future Cash Flows', type: 'list', defaultValue: [3000, 4200, 5800], required: true },
        { key: 'discountRate', label: 'Discount Rate (%)', type: 'number', defaultValue: 10, suffix: '%', required: true },
    ],
    results: [
        {
            label: 'Net Present Value',
            type: 'currency',
            calculate: (d) => financialService.calculateNpv({
                initialInvestment: d['initialInvestment'],
                cashFlows: d['cashFlows'].map(Number),
                discountRate: d['discountRate'] / 100
            })
        }
    ],
    insights: 'A positive **NPV** indicates that the projected earnings generated by a project or investment (in present dollars) exceeds the anticipated costs (also in present dollars).',
    formula: 'NPV = ∑ [CFt / (1 + r)^t] - Initial Investment'
};
